services:
  postgres:
    ports:
      - "5432:5432"

  hasir-api:
    ports:
      - "8080:8080"
    environment:
      MODE: development
    volumes:
      - ./config.json:/app/config.json:ro

  hasir-dashboard:
    ports:
      - "3000:3000"
